#!/bin/bash

cd `dirname $0`

#JAVA_HOME="/usr/lib/jvm/java-1.5.0-sun"
JAVA_HOME="/usr/local/lib/jvm/jdk1.6.0"
CONFIG_FILE="../capturer/src/main/resource/capturer.conf"
LIB_DIR="../lib"

JAVA_OPT="-server -Dsipana.config=$CONFIG_FILE" 

# Options for SNMP and JVM agents (remenber that JVM will run on ./bin directory)
#JAVA_OPT="${JAVA_OPT} -Dcom.sun.management.config.file=$JAVA_HOME/jre/lib/management/management.properties"

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LIB_DIR
CLASSPATH=$LIB_DIR/net.sourceforge.jpcap-0.01.16.jar:$LIB_DIR/JainSipRi1.2.jar:$LIB_DIR/JainSipApi1.2.jar:$LIB_DIR/jakarta-regexp-1.3.jar:$LIB_DIR/log4j-1.2.14.jar:$LIB_DIR/jetty-6.1.1.jar:$LIB_DIR/servlet-api-2.5-6.1.1.jar:$LIB_DIR/jetty-util-6.1.1.jar:$LIB_DIR/apache-activemq-4.1.1.jar:.:

export JAVA_HOME
export WORK_DIR
export LD_LIBRARY_PATH
export CLASSPATH

cd ./bin
java $JAVA_OPT br.com.voicetechnology.sipana.SipanaCapturer

